colore_preferito = input("Qual è il tuo colore preferito? ")
print("Il tuo colore preferito è " + colore_preferito)
print(f"Il tuo colore preferito è {colore_preferito}")
anni_persona = input("quanti anni hai?")
print("la persona ha " + anni_persona + " anni")
print(f"la persona ha {anni_persona} anni")
print(type(anni_persona))
anni_persona = int(anni_persona)
print(type(anni_persona) , "questo è il type dove aver trasformato la variabile anni_persona in un intero con int() poiche di base è una stringa")
# possiamo anche concatenare i metodo int() e input() nel print() senza dichiarare una variabile intermedia o possiamo anche unirli nell'inserimento dell'input stesso anni_persona = int(input("quanti anni hai?")) 
anni_persona_due = int(input("quanti anni ha la seconda persona?"))
print("la seconda persona ha " , anni_persona_due , " anni")
print(type(anni_persona_due) , "questo è il type dove aver trasformato la variabile anni_persona_due in un intero con int() poiche di base è una stringa")